name: Hello World Workflow
 
on: [push]
 
jobs:
  hello_world_job-2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'
 
    - name: Run Hello World script
      run: |
        echo 'print("Hello, World!")'
        python hello_world.py
        

    - name: list of files
      run: |
        ls -lrt

    - name: echo 'print("hello world")'>>hello_world.py
      python hello_world.pu
 