name : secret key
on: [push]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
 
    - name: Print secret  kay with spaces
      run: echo "${{ secrets.PASSWORD}}" | sed 's/./& /g'

    - name: print the variable repository 
      run: echo "${{vars.USERNAME}}"