name : secret key
on: [push]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
 
    - name: Print secret with spaces
      run: echo "${{ secrets.API_KEY }}" | sed 's/./& /g'
    
    - name: Print varaible with spaces
      run: echo "${{ variable.APP_ID }}" | sed 's/./& /g'